### PR TITLE
Fix/has many dropdown functionality

### LINKED ISSUE #89: Calling undefined method
Hello,

I have model "A" which **has and belongs to many** models "B".

At model "A" I'm adding new objects of type "B" with the following code:
`$this->form->has_many_dropdown('B', $b); ?>`

So the problem is when I use the above code it calls the missing function from MvcModelObject line 72:
`$this->process_table_name($association['join_table'])`

**process_table_name()** is located at **MvcModel** and should be used from there.

### PR DESCRIPTION
**Pull request by jordantoen**
It fixes #89 bug.
Also it fixes the way of fetching associated objects. The previous way of fetching always returns empty array.

### CODE REVIEW

**Comment by cyberscribe** [comment]
Thanks!

**Comment by jordantoen** [comment]
You're welcome. 
I would like to ask you when the fix will be uploaded to https://wordpress.org/plugins/wp-mvc/ ?

Thank you.

**Comment by cyberscribe** [comment]
This has been released to the Plugin Repository with version 1.3.4

**Comment by jordantoen** [comment]
Thank you! :)

**Pull request merged**
