### PR TITLE
optional 'extra_on' parameter added to defining 'joins' for find() method (and related to find())

### PR DESCRIPTION
**Pull request by polcodemichalkrawczyk**
This feature allows to add extra conditions in JOIN ... ON clause.
It makes sense only while using the LEFT JOIN or RIGHT JOIN. Default JOIN is equivalent of INNER JOIN and in this case using conditions in ON clause has the same effect as using it in WHERE clause.
Still - some more flexibility there.

### CODE REVIEW

**Comment by cyberscribe** [comment]
Thanks for this. Haven't been able to test it yet. If someone else can validate it doesn't break anything, I'm very happy to merge it in! :)

**Comment by cyberscribe** [comment]
Any further testing/validation on this? Sounds useful...

**Comment by polcodemichalkrawczyk** [comment]
well... backward compatibility is 100%.
I've done quite intensive testing myself but real testing will be possible only when other developers will need this feature.

**Comment by cyberscribe** [comment]
Thanks @polcodemichalkrawczyk

**Pull request merged**
