### PR TITLE
rolled back #184 due to fatal errors in testing

### PR DESCRIPTION
**Pull request by cyberscribe**
@justintilson please re-submit a pull request when this has been resolved--multiple existing multisite instances crashed after applying these changes.

### CODE REVIEW

**Comment by ngosselin-mn** [comment]
What fatal errors were you seeing?  That way I can look into them.

**Comment by cyberscribe** [comment]
It looks like for existing plugins that implement wp-mvc the autoloader can no longer find the right objects.

Note that I replaced the wp-mvc plugin inline (i.e. git pull) without deactivating/reactivating (which I believe is something the WP plugins repository would do).

Does this give you enough to go on to reproduce it?

Thanks again for your support of the project.

**Comment by ngosselin-mn** [comment]
@cyberscribe 

Ah, that is making sense, since the old plugins, would of used update_option(), vs update_site_option() for its options, meaning that they are in the main option tables vs a site's option table.

What probably needs to happen here, is to verify in both spots for the options, or to fallback if they aren't found in the new spot, ie: have some type of legacy support in place.

I will have to look at the code to see how that can be accomplished, only issue is I am not sure when I will get to it :).

**Comment by cyberscribe** [comment]
Thanks for getting to it when you can; will be great to have this in place in a backwards-compatible manner whenever it's ready to go.

**Pull request merged**
